[package]
name = "sunlo-tanstack"
version = "0.1.0"
description = "Sunlo: Social Language Learning"
authors = ["@michaelsnook"]
license = "be-nice"
repository = "https://github.com/michaelsnook/sunlo-tanrouter.git"
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.3.1", features = [] }
tauri-plugin-deep-link = "2.0.0"

# TODO I'm not sure why this has to be here but it fixes the build
tauri-plugin-updater = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
