/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/_user'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as UserProfileImport } from './routes/_user/profile'
import { Route as UserLearnImport } from './routes/_user/learn'
import { Route as UserGettingStartedImport } from './routes/_user/getting-started'
import { Route as UserFriendsImport } from './routes/_user/friends'
import { Route as UserAcceptInviteImport } from './routes/_user/accept-invite'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthSetNewPasswordImport } from './routes/_auth/set-new-password'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthFindAFriendImport } from './routes/_auth/find-a-friend'
import { Route as UserProfileIndexImport } from './routes/_user/profile.index'
import { Route as UserLearnIndexImport } from './routes/_user/learn.index'
import { Route as UserFriendsIndexImport } from './routes/_user/friends.index'
import { Route as UserProfileChangePasswordImport } from './routes/_user/profile.change-password'
import { Route as UserProfileChangeEmailConfirmImport } from './routes/_user/profile.change-email-confirm'
import { Route as UserProfileChangeEmailImport } from './routes/_user/profile.change-email'
import { Route as UserLearnQuickSearchImport } from './routes/_user/learn.quick-search'
import { Route as UserLearnAddDeckImport } from './routes/_user/learn.add-deck'
import { Route as UserLearnLangImport } from './routes/_user/learn.$lang'
import { Route as UserFriendsSearchImport } from './routes/_user/friends.search'
import { Route as UserFriendsInviteImport } from './routes/_user/friends.invite'
import { Route as UserFriendsUidImport } from './routes/_user/friends.$uid'
import { Route as UserLearnLangIndexImport } from './routes/_user/learn.$lang.index'
import { Route as UserLearnLangSearchImport } from './routes/_user/learn.$lang.search'
import { Route as UserLearnLangReviewImport } from './routes/_user/learn.$lang.review'
import { Route as UserLearnLangLibraryImport } from './routes/_user/learn.$lang.library'
import { Route as UserLearnLangDeckSettingsImport } from './routes/_user/learn.$lang.deck-settings'
import { Route as UserLearnLangAddPhraseImport } from './routes/_user/learn.$lang.add-phrase'
import { Route as UserFriendsSearchUidImport } from './routes/_user/friends.search.$uid'

// Create Virtual Routes

const PrivacyPolicyLazyImport = createFileRoute('/privacy-policy')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const ComponentsLazyImport = createFileRoute('/components')()

// Create/Update Routes

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const ComponentsLazyRoute = ComponentsLazyImport.update({
  path: '/components',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/components.lazy').then((d) => d.Route))

const UserRoute = UserImport.update({
  id: '/_user',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserProfileRoute = UserProfileImport.update({
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)

const UserLearnRoute = UserLearnImport.update({
  path: '/learn',
  getParentRoute: () => UserRoute,
} as any)

const UserGettingStartedRoute = UserGettingStartedImport.update({
  path: '/getting-started',
  getParentRoute: () => UserRoute,
} as any)

const UserFriendsRoute = UserFriendsImport.update({
  path: '/friends',
  getParentRoute: () => UserRoute,
} as any)

const UserAcceptInviteRoute = UserAcceptInviteImport.update({
  path: '/accept-invite',
  getParentRoute: () => UserRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSetNewPasswordRoute = AuthSetNewPasswordImport.update({
  path: '/set-new-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFindAFriendRoute = AuthFindAFriendImport.update({
  path: '/find-a-friend',
  getParentRoute: () => AuthRoute,
} as any)

const UserProfileIndexRoute = UserProfileIndexImport.update({
  path: '/',
  getParentRoute: () => UserProfileRoute,
} as any)

const UserLearnIndexRoute = UserLearnIndexImport.update({
  path: '/',
  getParentRoute: () => UserLearnRoute,
} as any)

const UserFriendsIndexRoute = UserFriendsIndexImport.update({
  path: '/',
  getParentRoute: () => UserFriendsRoute,
} as any)

const UserProfileChangePasswordRoute = UserProfileChangePasswordImport.update({
  path: '/change-password',
  getParentRoute: () => UserProfileRoute,
} as any)

const UserProfileChangeEmailConfirmRoute =
  UserProfileChangeEmailConfirmImport.update({
    path: '/change-email-confirm',
    getParentRoute: () => UserProfileRoute,
  } as any)

const UserProfileChangeEmailRoute = UserProfileChangeEmailImport.update({
  path: '/change-email',
  getParentRoute: () => UserProfileRoute,
} as any)

const UserLearnQuickSearchRoute = UserLearnQuickSearchImport.update({
  path: '/quick-search',
  getParentRoute: () => UserLearnRoute,
} as any)

const UserLearnAddDeckRoute = UserLearnAddDeckImport.update({
  path: '/add-deck',
  getParentRoute: () => UserLearnRoute,
} as any)

const UserLearnLangRoute = UserLearnLangImport.update({
  path: '/$lang',
  getParentRoute: () => UserLearnRoute,
} as any)

const UserFriendsSearchRoute = UserFriendsSearchImport.update({
  path: '/search',
  getParentRoute: () => UserFriendsRoute,
} as any)

const UserFriendsInviteRoute = UserFriendsInviteImport.update({
  path: '/invite',
  getParentRoute: () => UserFriendsRoute,
} as any)

const UserFriendsUidRoute = UserFriendsUidImport.update({
  path: '/$uid',
  getParentRoute: () => UserFriendsRoute,
} as any)

const UserLearnLangIndexRoute = UserLearnLangIndexImport.update({
  path: '/',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserLearnLangSearchRoute = UserLearnLangSearchImport.update({
  path: '/search',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserLearnLangReviewRoute = UserLearnLangReviewImport.update({
  path: '/review',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserLearnLangLibraryRoute = UserLearnLangLibraryImport.update({
  path: '/library',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserLearnLangDeckSettingsRoute = UserLearnLangDeckSettingsImport.update({
  path: '/deck-settings',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserLearnLangAddPhraseRoute = UserLearnLangAddPhraseImport.update({
  path: '/add-phrase',
  getParentRoute: () => UserLearnLangRoute,
} as any)

const UserFriendsSearchUidRoute = UserFriendsSearchUidImport.update({
  path: '/$uid',
  getParentRoute: () => UserFriendsSearchRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/find-a-friend': {
      id: '/_auth/find-a-friend'
      path: '/find-a-friend'
      fullPath: '/find-a-friend'
      preLoaderRoute: typeof AuthFindAFriendImport
      parentRoute: typeof AuthImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/set-new-password': {
      id: '/_auth/set-new-password'
      path: '/set-new-password'
      fullPath: '/set-new-password'
      preLoaderRoute: typeof AuthSetNewPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_user/accept-invite': {
      id: '/_user/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof UserAcceptInviteImport
      parentRoute: typeof UserImport
    }
    '/_user/friends': {
      id: '/_user/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof UserFriendsImport
      parentRoute: typeof UserImport
    }
    '/_user/getting-started': {
      id: '/_user/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof UserGettingStartedImport
      parentRoute: typeof UserImport
    }
    '/_user/learn': {
      id: '/_user/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof UserLearnImport
      parentRoute: typeof UserImport
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileImport
      parentRoute: typeof UserImport
    }
    '/_user/friends/$uid': {
      id: '/_user/friends/$uid'
      path: '/$uid'
      fullPath: '/friends/$uid'
      preLoaderRoute: typeof UserFriendsUidImport
      parentRoute: typeof UserFriendsImport
    }
    '/_user/friends/invite': {
      id: '/_user/friends/invite'
      path: '/invite'
      fullPath: '/friends/invite'
      preLoaderRoute: typeof UserFriendsInviteImport
      parentRoute: typeof UserFriendsImport
    }
    '/_user/friends/search': {
      id: '/_user/friends/search'
      path: '/search'
      fullPath: '/friends/search'
      preLoaderRoute: typeof UserFriendsSearchImport
      parentRoute: typeof UserFriendsImport
    }
    '/_user/learn/$lang': {
      id: '/_user/learn/$lang'
      path: '/$lang'
      fullPath: '/learn/$lang'
      preLoaderRoute: typeof UserLearnLangImport
      parentRoute: typeof UserLearnImport
    }
    '/_user/learn/add-deck': {
      id: '/_user/learn/add-deck'
      path: '/add-deck'
      fullPath: '/learn/add-deck'
      preLoaderRoute: typeof UserLearnAddDeckImport
      parentRoute: typeof UserLearnImport
    }
    '/_user/learn/quick-search': {
      id: '/_user/learn/quick-search'
      path: '/quick-search'
      fullPath: '/learn/quick-search'
      preLoaderRoute: typeof UserLearnQuickSearchImport
      parentRoute: typeof UserLearnImport
    }
    '/_user/profile/change-email': {
      id: '/_user/profile/change-email'
      path: '/change-email'
      fullPath: '/profile/change-email'
      preLoaderRoute: typeof UserProfileChangeEmailImport
      parentRoute: typeof UserProfileImport
    }
    '/_user/profile/change-email-confirm': {
      id: '/_user/profile/change-email-confirm'
      path: '/change-email-confirm'
      fullPath: '/profile/change-email-confirm'
      preLoaderRoute: typeof UserProfileChangeEmailConfirmImport
      parentRoute: typeof UserProfileImport
    }
    '/_user/profile/change-password': {
      id: '/_user/profile/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof UserProfileChangePasswordImport
      parentRoute: typeof UserProfileImport
    }
    '/_user/friends/': {
      id: '/_user/friends/'
      path: '/'
      fullPath: '/friends/'
      preLoaderRoute: typeof UserFriendsIndexImport
      parentRoute: typeof UserFriendsImport
    }
    '/_user/learn/': {
      id: '/_user/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof UserLearnIndexImport
      parentRoute: typeof UserLearnImport
    }
    '/_user/profile/': {
      id: '/_user/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof UserProfileIndexImport
      parentRoute: typeof UserProfileImport
    }
    '/_user/friends/search/$uid': {
      id: '/_user/friends/search/$uid'
      path: '/$uid'
      fullPath: '/friends/search/$uid'
      preLoaderRoute: typeof UserFriendsSearchUidImport
      parentRoute: typeof UserFriendsSearchImport
    }
    '/_user/learn/$lang/add-phrase': {
      id: '/_user/learn/$lang/add-phrase'
      path: '/add-phrase'
      fullPath: '/learn/$lang/add-phrase'
      preLoaderRoute: typeof UserLearnLangAddPhraseImport
      parentRoute: typeof UserLearnLangImport
    }
    '/_user/learn/$lang/deck-settings': {
      id: '/_user/learn/$lang/deck-settings'
      path: '/deck-settings'
      fullPath: '/learn/$lang/deck-settings'
      preLoaderRoute: typeof UserLearnLangDeckSettingsImport
      parentRoute: typeof UserLearnLangImport
    }
    '/_user/learn/$lang/library': {
      id: '/_user/learn/$lang/library'
      path: '/library'
      fullPath: '/learn/$lang/library'
      preLoaderRoute: typeof UserLearnLangLibraryImport
      parentRoute: typeof UserLearnLangImport
    }
    '/_user/learn/$lang/review': {
      id: '/_user/learn/$lang/review'
      path: '/review'
      fullPath: '/learn/$lang/review'
      preLoaderRoute: typeof UserLearnLangReviewImport
      parentRoute: typeof UserLearnLangImport
    }
    '/_user/learn/$lang/search': {
      id: '/_user/learn/$lang/search'
      path: '/search'
      fullPath: '/learn/$lang/search'
      preLoaderRoute: typeof UserLearnLangSearchImport
      parentRoute: typeof UserLearnLangImport
    }
    '/_user/learn/$lang/': {
      id: '/_user/learn/$lang/'
      path: '/'
      fullPath: '/learn/$lang/'
      preLoaderRoute: typeof UserLearnLangIndexImport
      parentRoute: typeof UserLearnLangImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthFindAFriendRoute,
    AuthForgotPasswordRoute,
    AuthLoginRoute,
    AuthSetNewPasswordRoute,
    AuthSignupRoute,
  }),
  UserRoute: UserRoute.addChildren({
    UserAcceptInviteRoute,
    UserFriendsRoute: UserFriendsRoute.addChildren({
      UserFriendsUidRoute,
      UserFriendsInviteRoute,
      UserFriendsSearchRoute: UserFriendsSearchRoute.addChildren({
        UserFriendsSearchUidRoute,
      }),
      UserFriendsIndexRoute,
    }),
    UserGettingStartedRoute,
    UserLearnRoute: UserLearnRoute.addChildren({
      UserLearnLangRoute: UserLearnLangRoute.addChildren({
        UserLearnLangAddPhraseRoute,
        UserLearnLangDeckSettingsRoute,
        UserLearnLangLibraryRoute,
        UserLearnLangReviewRoute,
        UserLearnLangSearchRoute,
        UserLearnLangIndexRoute,
      }),
      UserLearnAddDeckRoute,
      UserLearnQuickSearchRoute,
      UserLearnIndexRoute,
    }),
    UserProfileRoute: UserProfileRoute.addChildren({
      UserProfileChangeEmailRoute,
      UserProfileChangeEmailConfirmRoute,
      UserProfileChangePasswordRoute,
      UserProfileIndexRoute,
    }),
  }),
  ComponentsLazyRoute,
  DashboardLazyRoute,
  PrivacyPolicyLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_user",
        "/components",
        "/dashboard",
        "/privacy-policy"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/find-a-friend",
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/set-new-password",
        "/_auth/signup"
      ]
    },
    "/_user": {
      "filePath": "_user.tsx",
      "children": [
        "/_user/accept-invite",
        "/_user/friends",
        "/_user/getting-started",
        "/_user/learn",
        "/_user/profile"
      ]
    },
    "/components": {
      "filePath": "components.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.tsx"
    },
    "/_auth/find-a-friend": {
      "filePath": "_auth/find-a-friend.tsx",
      "parent": "/_auth"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/set-new-password": {
      "filePath": "_auth/set-new-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/_user/accept-invite": {
      "filePath": "_user/accept-invite.tsx",
      "parent": "/_user"
    },
    "/_user/friends": {
      "filePath": "_user/friends.tsx",
      "parent": "/_user",
      "children": [
        "/_user/friends/$uid",
        "/_user/friends/invite",
        "/_user/friends/search",
        "/_user/friends/"
      ]
    },
    "/_user/getting-started": {
      "filePath": "_user/getting-started.tsx",
      "parent": "/_user"
    },
    "/_user/learn": {
      "filePath": "_user/learn.tsx",
      "parent": "/_user",
      "children": [
        "/_user/learn/$lang",
        "/_user/learn/add-deck",
        "/_user/learn/quick-search",
        "/_user/learn/"
      ]
    },
    "/_user/profile": {
      "filePath": "_user/profile.tsx",
      "parent": "/_user",
      "children": [
        "/_user/profile/change-email",
        "/_user/profile/change-email-confirm",
        "/_user/profile/change-password",
        "/_user/profile/"
      ]
    },
    "/_user/friends/$uid": {
      "filePath": "_user/friends.$uid.tsx",
      "parent": "/_user/friends"
    },
    "/_user/friends/invite": {
      "filePath": "_user/friends.invite.tsx",
      "parent": "/_user/friends"
    },
    "/_user/friends/search": {
      "filePath": "_user/friends.search.tsx",
      "parent": "/_user/friends",
      "children": [
        "/_user/friends/search/$uid"
      ]
    },
    "/_user/learn/$lang": {
      "filePath": "_user/learn.$lang.tsx",
      "parent": "/_user/learn",
      "children": [
        "/_user/learn/$lang/add-phrase",
        "/_user/learn/$lang/deck-settings",
        "/_user/learn/$lang/library",
        "/_user/learn/$lang/review",
        "/_user/learn/$lang/search",
        "/_user/learn/$lang/"
      ]
    },
    "/_user/learn/add-deck": {
      "filePath": "_user/learn.add-deck.tsx",
      "parent": "/_user/learn"
    },
    "/_user/learn/quick-search": {
      "filePath": "_user/learn.quick-search.tsx",
      "parent": "/_user/learn"
    },
    "/_user/profile/change-email": {
      "filePath": "_user/profile.change-email.tsx",
      "parent": "/_user/profile"
    },
    "/_user/profile/change-email-confirm": {
      "filePath": "_user/profile.change-email-confirm.tsx",
      "parent": "/_user/profile"
    },
    "/_user/profile/change-password": {
      "filePath": "_user/profile.change-password.tsx",
      "parent": "/_user/profile"
    },
    "/_user/friends/": {
      "filePath": "_user/friends.index.tsx",
      "parent": "/_user/friends"
    },
    "/_user/learn/": {
      "filePath": "_user/learn.index.tsx",
      "parent": "/_user/learn"
    },
    "/_user/profile/": {
      "filePath": "_user/profile.index.tsx",
      "parent": "/_user/profile"
    },
    "/_user/friends/search/$uid": {
      "filePath": "_user/friends.search.$uid.tsx",
      "parent": "/_user/friends/search"
    },
    "/_user/learn/$lang/add-phrase": {
      "filePath": "_user/learn.$lang.add-phrase.tsx",
      "parent": "/_user/learn/$lang"
    },
    "/_user/learn/$lang/deck-settings": {
      "filePath": "_user/learn.$lang.deck-settings.tsx",
      "parent": "/_user/learn/$lang"
    },
    "/_user/learn/$lang/library": {
      "filePath": "_user/learn.$lang.library.tsx",
      "parent": "/_user/learn/$lang"
    },
    "/_user/learn/$lang/review": {
      "filePath": "_user/learn.$lang.review.tsx",
      "parent": "/_user/learn/$lang"
    },
    "/_user/learn/$lang/search": {
      "filePath": "_user/learn.$lang.search.tsx",
      "parent": "/_user/learn/$lang"
    },
    "/_user/learn/$lang/": {
      "filePath": "_user/learn.$lang.index.tsx",
      "parent": "/_user/learn/$lang"
    }
  }
}
ROUTE_MANIFEST_END */
